// Company Names Lookup - Maps ticker symbols to full company names
export const COMPANY_NAMES = {
  // Mega Cap Tech
  'AAPL': 'Apple Inc.',
  'MSFT': 'Microsoft Corporation',
  'GOOGL': 'Alphabet Inc. (Class A)',
  'GOOG': 'Alphabet Inc. (Class C)',
  'AMZN': 'Amazon.com, Inc.',
  'META': 'Meta Platforms, Inc.',
  'NVDA': 'NVIDIA Corporation',
  'TSLA': 'Tesla, Inc.',
  'TSM': 'Taiwan Semiconductor',
  'AVGO': 'Broadcom Inc.',
  'ORCL': 'Oracle Corporation',
  'ADBE': 'Adobe Inc.',
  'CRM': 'Salesforce, Inc.',
  'AMD': 'Advanced Micro Devices',
  'NFLX': 'Netflix, Inc.',
  'INTC': 'Intel Corporation',
  'CSCO': 'Cisco Systems, Inc.',
  'QCOM': 'Qualcomm Incorporated',
  'TXN': 'Texas Instruments',
  'IBM': 'International Business Machines',
  'INTU': 'Intuit Inc.',
  'AMAT': 'Applied Materials, Inc.',
  'NOW': 'ServiceNow, Inc.',
  'SHOP': 'Shopify Inc.',
  'UBER': 'Uber Technologies, Inc.',
  'SNOW': 'Snowflake Inc.',
  'SQ': 'Block, Inc.',
  'PLTR': 'Palantir Technologies',
  'NET': 'Cloudflare, Inc.',
  'CRWD': 'CrowdStrike Holdings',
  'PANW': 'Palo Alto Networks',
  'ZS': 'Zscaler, Inc.',
  'DDOG': 'Datadog, Inc.',
  'MDB': 'MongoDB, Inc.',
  'WDAY': 'Workday, Inc.',
  'ZM': 'Zoom Video Communications',
  'DOCU': 'DocuSign, Inc.',
  'OKTA': 'Okta, Inc.',
  'TWLO': 'Twilio Inc.',
  'U': 'Unity Software Inc.',
  'PATH': 'UiPath Inc.',
  'COIN': 'Coinbase Global, Inc.',
  'HOOD': 'Robinhood Markets, Inc.',
  'SOFI': 'SoFi Technologies, Inc.',
  'RBLX': 'Roblox Corporation',
  'SNAP': 'Snap Inc.',
  'PINS': 'Pinterest, Inc.',
  'SPOT': 'Spotify Technology S.A.',
  'ROKU': 'Roku, Inc.',
  'TTD': 'The Trade Desk, Inc.',

  // Financial
  'JPM': 'JPMorgan Chase & Co.',
  'V': 'Visa Inc.',
  'MA': 'Mastercard Incorporated',
  'BAC': 'Bank of America Corp.',
  'WFC': 'Wells Fargo & Company',
  'C': 'Citigroup Inc.',
  'GS': 'Goldman Sachs Group',
  'MS': 'Morgan Stanley',
  'BLK': 'BlackRock, Inc.',
  'SCHW': 'Charles Schwab Corp.',
  'AXP': 'American Express Co.',
  'SPGI': 'S&P Global Inc.',
  'CME': 'CME Group Inc.',
  'ICE': 'Intercontinental Exchange',
  'CB': 'Chubb Limited',
  'PGR': 'Progressive Corporation',
  'MMC': 'Marsh & McLennan',
  'AON': 'Aon plc',
  'MET': 'MetLife, Inc.',
  'PRU': 'Prudential Financial',
  'TFC': 'Truist Financial Corp.',
  'USB': 'U.S. Bancorp',
  'PNC': 'PNC Financial Services',
  'BK': 'Bank of New York Mellon',
  'COF': 'Capital One Financial',
  'AIG': 'American International Group',
  'TRV': 'Travelers Companies',

  // Healthcare
  'UNH': 'UnitedHealth Group Inc.',
  'JNJ': 'Johnson & Johnson',
  'LLY': 'Eli Lilly and Company',
  'PFE': 'Pfizer Inc.',
  'ABBV': 'AbbVie Inc.',
  'MRK': 'Merck & Co., Inc.',
  'TMO': 'Thermo Fisher Scientific',
  'ABT': 'Abbott Laboratories',
  'DHR': 'Danaher Corporation',
  'BMY': 'Bristol-Myers Squibb',
  'AMGN': 'Amgen Inc.',
  'GILD': 'Gilead Sciences, Inc.',
  'CVS': 'CVS Health Corporation',
  'ELV': 'Elevance Health, Inc.',
  'CI': 'The Cigna Group',
  'SYK': 'Stryker Corporation',
  'ISRG': 'Intuitive Surgical, Inc.',
  'BSX': 'Boston Scientific Corp.',
  'VRTX': 'Vertex Pharmaceuticals',
  'REGN': 'Regeneron Pharmaceuticals',
  'MDT': 'Medtronic plc',
  'ZTS': 'Zoetis Inc.',
  'HUM': 'Humana Inc.',
  'MCK': 'McKesson Corporation',
  'MRNA': 'Moderna, Inc.',
  'BIIB': 'Biogen Inc.',
  'ILMN': 'Illumina, Inc.',
  'DXCM': 'DexCom, Inc.',

  // Consumer
  'WMT': 'Walmart Inc.',
  'HD': 'Home Depot, Inc.',
  'COST': 'Costco Wholesale Corp.',
  'PG': 'Procter & Gamble Co.',
  'KO': 'Coca-Cola Company',
  'PEP': 'PepsiCo, Inc.',
  'MCD': "McDonald's Corporation",
  'NKE': 'NIKE, Inc.',
  'SBUX': 'Starbucks Corporation',
  'TGT': 'Target Corporation',
  'LOW': "Lowe's Companies, Inc.",
  'TJX': 'TJX Companies, Inc.',
  'BKNG': 'Booking Holdings Inc.',
  'MAR': 'Marriott International',
  'CMG': 'Chipotle Mexican Grill',
  'ORLY': "O'Reilly Automotive",
  'AZO': 'AutoZone, Inc.',
  'ROST': 'Ross Stores, Inc.',
  'DG': 'Dollar General Corp.',
  'DLTR': 'Dollar Tree, Inc.',
  'YUM': 'Yum! Brands, Inc.',
  'ABNB': 'Airbnb, Inc.',
  'EBAY': 'eBay Inc.',
  'ETSY': 'Etsy, Inc.',
  'DASH': 'DoorDash, Inc.',
  'LYFT': 'Lyft, Inc.',
  'GM': 'General Motors Company',
  'F': 'Ford Motor Company',
  'RIVN': 'Rivian Automotive, Inc.',
  'LCID': 'Lucid Group, Inc.',
  'NIO': 'NIO Inc.',
  'LI': 'Li Auto Inc.',
  'XPEV': 'XPeng Inc.',

  // Industrial
  'CAT': 'Caterpillar Inc.',
  'GE': 'General Electric Co.',
  'HON': 'Honeywell International',
  'UPS': 'United Parcel Service',
  'UNP': 'Union Pacific Corporation',
  'BA': 'Boeing Company',
  'RTX': 'RTX Corporation',
  'LMT': 'Lockheed Martin Corp.',
  'DE': 'Deere & Company',
  'MMM': '3M Company',
  'FDX': 'FedEx Corporation',
  'GD': 'General Dynamics Corp.',
  'NOC': 'Northrop Grumman Corp.',
  'CSX': 'CSX Corporation',
  'NSC': 'Norfolk Southern Corp.',
  'WM': 'Waste Management, Inc.',
  'EMR': 'Emerson Electric Co.',
  'ITW': 'Illinois Tool Works',
  'ETN': 'Eaton Corporation',
  'PH': 'Parker-Hannifin Corp.',
  'CARR': 'Carrier Global Corp.',
  'OTIS': 'Otis Worldwide Corp.',
  'JCI': 'Johnson Controls Intl.',
  'ROK': 'Rockwell Automation',

  // Energy
  'XOM': 'Exxon Mobil Corporation',
  'CVX': 'Chevron Corporation',
  'COP': 'ConocoPhillips',
  'EOG': 'EOG Resources, Inc.',
  'SLB': 'Schlumberger Limited',
  'OXY': 'Occidental Petroleum',
  'MPC': 'Marathon Petroleum Corp.',
  'PSX': 'Phillips 66',
  'VLO': 'Valero Energy Corp.',
  'PXD': 'Pioneer Natural Resources',
  'DVN': 'Devon Energy Corp.',
  'HES': 'Hess Corporation',
  'HAL': 'Halliburton Company',
  'KMI': 'Kinder Morgan, Inc.',
  'WMB': 'Williams Companies, Inc.',
  'OKE': 'ONEOK, Inc.',
  'FANG': 'Diamondback Energy',

  // Communication Services
  'T': 'AT&T Inc.',
  'VZ': 'Verizon Communications',
  'TMUS': 'T-Mobile US, Inc.',
  'DIS': 'Walt Disney Company',
  'CMCSA': 'Comcast Corporation',
  'CHTR': 'Charter Communications',
  'EA': 'Electronic Arts Inc.',
  'ATVI': 'Activision Blizzard',
  'TTWO': 'Take-Two Interactive',
  'WBD': 'Warner Bros. Discovery',
  'PARA': 'Paramount Global',
  'LYV': 'Live Nation Entertainment',
  'MTCH': 'Match Group, Inc.',

  // Materials
  'LIN': 'Linde plc',
  'APD': 'Air Products & Chemicals',
  'SHW': 'Sherwin-Williams Co.',
  'ECL': 'Ecolab Inc.',
  'DD': 'DuPont de Nemours',
  'DOW': 'Dow Inc.',
  'FCX': 'Freeport-McMoRan Inc.',
  'NUE': 'Nucor Corporation',
  'NEM': 'Newmont Corporation',
  'CTVA': 'Corteva, Inc.',
  'ALB': 'Albemarle Corporation',
  'VMC': 'Vulcan Materials Co.',
  'MLM': 'Martin Marietta Materials',

  // Real Estate
  'AMT': 'American Tower Corp.',
  'PLD': 'Prologis, Inc.',
  'CCI': 'Crown Castle Inc.',
  'EQIX': 'Equinix, Inc.',
  'SPG': 'Simon Property Group',
  'PSA': 'Public Storage',
  'DLR': 'Digital Realty Trust',
  'O': 'Realty Income Corp.',
  'WELL': 'Welltower Inc.',
  'AVB': 'AvalonBay Communities',
  'EQR': 'Equity Residential',
  'VICI': 'VICI Properties Inc.',
  'SBAC': 'SBA Communications',
  'ARE': 'Alexandria Real Estate',

  // Utilities
  'NEE': 'NextEra Energy, Inc.',
  'DUK': 'Duke Energy Corporation',
  'SO': 'Southern Company',
  'D': 'Dominion Energy, Inc.',
  'SRE': 'Sempra',
  'AEP': 'American Electric Power',
  'EXC': 'Exelon Corporation',
  'XEL': 'Xcel Energy Inc.',
  'ED': 'Consolidated Edison',
  'PCG': 'PG&E Corporation',
  'WEC': 'WEC Energy Group',
  'ES': 'Eversource Energy',
  'AWK': 'American Water Works',

  // ETFs
  'SPY': 'SPDR S&P 500 ETF Trust',
  'QQQ': 'Invesco QQQ Trust',
  'IWM': 'iShares Russell 2000 ETF',
  'DIA': 'SPDR Dow Jones Industrial',
  'VTI': 'Vanguard Total Stock Market',
  'VOO': 'Vanguard S&P 500 ETF',
  'VXX': 'iPath Series B S&P 500 VIX',
  'GLD': 'SPDR Gold Shares',
  'SLV': 'iShares Silver Trust',
  'TLT': 'iShares 20+ Year Treasury',
  'XLF': 'Financial Select Sector SPDR',
  'XLE': 'Energy Select Sector SPDR',
  'XLK': 'Technology Select Sector SPDR',
  'XLV': 'Health Care Select Sector SPDR',
  'XLI': 'Industrial Select Sector SPDR',
  'XLY': 'Consumer Discretionary SPDR',
  'XLP': 'Consumer Staples Select SPDR',
  'XLU': 'Utilities Select Sector SPDR',
  'XLB': 'Materials Select Sector SPDR',
  'XLRE': 'Real Estate Select Sector SPDR',
  'ARKK': 'ARK Innovation ETF',
  'ARKF': 'ARK Fintech Innovation ETF',
  'ARKG': 'ARK Genomic Revolution ETF',
  'ARKW': 'ARK Next Generation Internet',
  'SOXL': 'Direxion Semiconductor Bull 3X',
  'SOXS': 'Direxion Semiconductor Bear 3X',
  'TQQQ': 'ProShares UltraPro QQQ',
  'SQQQ': 'ProShares UltraPro Short QQQ',

  // Crypto-related
  'MSTR': 'MicroStrategy Incorporated',
  'MARA': 'Marathon Digital Holdings',
  'RIOT': 'Riot Platforms, Inc.',
  'HUT': 'Hut 8 Mining Corp',
  'BITF': 'Bitfarms Ltd.',
  'CLSK': 'CleanSpark, Inc.',

  // Meme Stocks / Popular Trading
  'GME': 'GameStop Corp.',
  'AMC': 'AMC Entertainment Holdings',
  'BB': 'BlackBerry Limited',
  'BBBY': 'Bed Bath & Beyond Inc.',
  'SPCE': 'Virgin Galactic Holdings',
  'WISH': 'ContextLogic Inc.',
  'CLOV': 'Clover Health Investments',

  // Semiconductors
  'MU': 'Micron Technology, Inc.',
  'LRCX': 'Lam Research Corporation',
  'KLAC': 'KLA Corporation',
  'MRVL': 'Marvell Technology, Inc.',
  'ON': 'ON Semiconductor Corp.',
  'ADI': 'Analog Devices, Inc.',
  'NXPI': 'NXP Semiconductors N.V.',
  'SWKS': 'Skyworks Solutions, Inc.',
  'MPWR': 'Monolithic Power Systems',
  'ARM': 'Arm Holdings plc',
  'SMCI': 'Super Micro Computer',

  // AI / Cloud
  'AI': 'C3.ai, Inc.',
  'BBAI': 'BigBear.ai Holdings',
  'SOUN': 'SoundHound AI, Inc.',
  'UPST': 'Upstart Holdings, Inc.',

  // Biotech
  'NVAX': 'Novavax, Inc.',
  'SGEN': 'Seagen Inc.',
  'EXAS': 'Exact Sciences Corp.',
  'SRPT': 'Sarepta Therapeutics',
  'ALNY': 'Alnylam Pharmaceuticals',
  'BMRN': 'BioMarin Pharmaceutical'
};

// Helper function to get company name with fallback
export const getCompanyName = (symbol) => {
  return COMPANY_NAMES[symbol?.toUpperCase()] || null;
};

// COMPREHENSIVE STOCK LIST - 200+ stocks across all sectors for thorough analysis
export const PRIORITY_STOCKS = [
  // Tier 1: Most Active & Liquid (scan first for quick results)
  'NVDA', 'TSLA', 'AAPL', 'AMD', 'META', 'MSFT', 'AMZN', 'GOOGL', 'NFLX', 'COIN',
  'PLTR', 'SOFI', 'NIO', 'RIVN', 'LCID', 'F', 'GM', 'BA', 'DIS', 'PYPL',
  // Tier 2: Large-Cap Tech
  'CRM', 'ADBE', 'INTC', 'MU', 'QCOM', 'AVGO', 'ORCL', 'IBM', 'NOW', 'AMAT',
  'LRCX', 'ADI', 'KLAC', 'SNPS', 'CDNS', 'MRVL', 'NXPI', 'ON', 'MCHP', 'TXN',
  // Tier 3: Software & Cloud
  'SHOP', 'SQ', 'SNOW', 'DDOG', 'NET', 'CRWD', 'ZS', 'PANW', 'FTNT', 'OKTA',
  'MDB', 'WDAY', 'TEAM', 'HUBS', 'DOCN', 'CFLT', 'PATH', 'BILL', 'SPLK', 'ESTC',
  // Tier 4: E-commerce & Internet
  'ROKU', 'UBER', 'LYFT', 'DASH', 'ABNB', 'RBLX', 'PINS', 'SNAP', 'TWLO', 'ZM',
  'DOCU', 'SPOT', 'MELI', 'SE', 'BABA', 'JD', 'PDD', 'BIDU', 'EBAY', 'ETSY',
  // Tier 5: Streaming & Entertainment
  'TTD', 'U', 'EA', 'TTWO', 'DKNG', 'PENN', 'MGM', 'LYV', 'MTCH', 'BMBL',
  // Tier 6: Fintech & Payments
  'V', 'MA', 'AXP', 'HOOD', 'AFRM', 'UPST', 'NU', 'LC', 'MQ', 'FOUR',
  // Tier 7: Major Banks & Finance
  'JPM', 'BAC', 'WFC', 'C', 'GS', 'MS', 'BLK', 'SCHW', 'COF', 'USB',
  'PNC', 'TFC', 'FITB', 'KEY', 'RF', 'CFG', 'MTB', 'HBAN', 'ZION', 'ALLY',
  // Tier 8: Healthcare & Pharma
  'UNH', 'JNJ', 'PFE', 'MRK', 'ABBV', 'LLY', 'BMY', 'GILD', 'AMGN', 'REGN',
  'VRTX', 'BIIB', 'MRNA', 'BNTX', 'NVAX', 'ZBH', 'SYK', 'MDT', 'BSX', 'ABT',
  'TMO', 'DHR', 'ISRG', 'EW', 'DXCM', 'PODD', 'ALNY', 'EXAS', 'ILMN', 'BGNE',
  // Tier 9: Energy - Oil & Gas
  'XOM', 'CVX', 'COP', 'SLB', 'EOG', 'MPC', 'VLO', 'PSX', 'OXY', 'HAL',
  'DVN', 'FANG', 'HES', 'MRO', 'APA', 'BKR', 'NOV', 'RRC', 'AR', 'EQT',
  // Tier 10: Clean Energy & EV
  'FSLR', 'ENPH', 'SEDG', 'RUN', 'PLUG', 'FCEL', 'BE', 'BLDP', 'CHPT', 'EVGO',
  'BLNK', 'GNRC', 'STEM', 'NOVA', 'JKS', 'CSIQ', 'DQ', 'MAXN', 'ARRY', 'SPWR',
  // Tier 11: Consumer & Retail
  'WMT', 'COST', 'TGT', 'HD', 'LOW', 'MCD', 'SBUX', 'NKE', 'LULU', 'CMG',
  'YUM', 'DPZ', 'WING', 'SHAK', 'CAVA', 'EAT', 'TXRH', 'PG', 'KO', 'PEP',
  'GPS', 'ANF', 'AEO', 'URBN', 'RL', 'PVH', 'TPR', 'VFC', 'CHWY', 'CHEWY',
  // Tier 12: Industrial & Aerospace
  'CAT', 'DE', 'HON', 'GE', 'MMM', 'UPS', 'FDX', 'LMT', 'RTX', 'NOC',
  'GD', 'TDG', 'HWM', 'TXT', 'EMR', 'ETN', 'ITW', 'PH', 'ROK', 'AME',
  // Tier 13: Travel & Leisure
  'EXPE', 'BKNG', 'MAR', 'HLT', 'WYNN', 'LVS', 'CZR', 'RCL', 'CCL', 'NCLH',
  'DAL', 'UAL', 'LUV', 'AAL', 'ALK', 'JBLU', 'RACE', 'H', 'WH', 'IHG',
  // Tier 14: Materials & Mining
  'FCX', 'NEM', 'GOLD', 'AEM', 'NUE', 'STLD', 'CLF', 'X', 'AA', 'CENX',
  'MP', 'LAC', 'ALB', 'SQM', 'LTHM', 'CC', 'FMC', 'CF', 'MOS', 'SMG',
  // Tier 15: ETFs for market context
  'SPY', 'QQQ', 'IWM', 'DIA', 'XLF', 'XLE', 'XLK', 'XLV', 'XLI', 'XLB',
  'XLY', 'XLP', 'XLU', 'XLRE', 'XLC', 'ARKK', 'ARKG', 'ARKF', 'SOXX', 'SMH',
  'KWEB', 'FXI', 'EEM', 'EFA', 'VWO', 'GDX', 'SLV', 'GLD', 'TLT', 'HYG'
];
